package org.kogito.serverless.demo

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.node.ObjectNode
import java.lang.Integer

rule "Auto Approve"
ruleflow-group "neworder"
no-loop
    when
        $w : JsonNode()
        eval( Integer.parseInt($w.get("cost").asText()) < 1000)
    then
        ( (ObjectNode) $w ).put("decision", "Approved");
end

rule "Needs Manager Approval"
ruleflow-group "neworder"
no-loop
    when
        $w : JsonNode()
        eval( Integer.parseInt($w.get("cost").asText()) >= 1000)
    then
        ( (ObjectNode) $w ).put("decision", "NeedManagerApproval");
end

