apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: orders-demo
spec:
  type: RemoteSource
  gitSource:
    uri: "https://github.com/Serverless-Workflow-Kogito/orders-demo"
  #mavenMirrorURL: ""
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: orders-demo
spec:
  kafka:
    useKogitoInfra: true